export default {
	ChinaLanguage:{
		gameDe:'游戏扣款',
		deductions:'扣款类型',
		code:"邀请码",
		Invite:"邀请关系",
		community:'我的社区',
		reward:"推广奖励",
		copy:"复制",
		cumulative:"已获得收益累计",
		feedback:"已获得门票反馈累计",
		withhold:"门票扣款", 
		backgd:"背景音乐",
		contractLevel:"合约等级",
		DailyInnings:"合约每日游戏局数赠与",
		today:"今日已玩局数",
		maturity:"合约到期时间",
		lockUp:"合约锁仓",
		lockUpNum:'获取更多游戏次数',
		rule:"合约规则",
		lowNum:"低倍数",
		heightNum:"高倍数",
		rising:"底注",
		risingTitle:"全天开放 固定投注",
		risingTitle2:"限时开放 可选倍数",
		matching:"立即匹配",
		choose:"请选择",
		
		minersReward:"矿工费用奖励系数",
		earned:"已获得收益累计",
		rewards:'点击查看推广奖励',
		time:"时间",
		amount:"金额",
		confirmBinding:"确认绑定",
		lock:'锁仓',
		contractPeriod:'合约周期',
		day:"天",
		everyday:'每日游戏局属赠予:',
		contractNum:'局',
		getCode:"请输入邀请码",
		people:"人",
		invitation:"邀请绑定",
		gameRecord:"游戏记录",
		SetUp:"设置",
		
		addBind:'添加绑定',
		sendCode:"请输入邀请码",
		unbind:"去绑定",
		bound:"已绑定",
		myCommunity:"我的社群",
		
		accumulated:"已获得门票反馈累计",
	},
	EnglisghLanguage:{
		earned:"Earned cumulative",
		rewards:'Click to view promotion rewards',
		time:"time",
		amount:"Amount",
		confirmBinding:"Confirm binding",
		lock:'Lock up',
		contractPeriod:'Contract period',
		day:"day",
		everyday:'Daily game board gift:',
		contractNum:'games',
		getCode:"Please enter the invitation code",
		addBind:'Add binding',
		sendCode:"Please enter the invitation code",
		unbind:"Unbind",
		bound:"Bound",
		myCommunity:"My community",
		myCommunity:"My community",
		accumulated:"Ticket feedback accumulated",
		people:"people",
		choose:"Please select a",
		
		gameDe:'The game is deductions',
		deductions:'Deductions type',
		code:"Invitation code",
		Invite:"Invite relationship",
		community:'My community',
		reward:"Promotion rewards",
		copy:"copy",
		cumulative:"Accumulated revenue has been obtained",
		feedback:"Accumulated ticket feedback has been obtained",
		withhold:"Tickets for deductions",
		backgd:"background music ",
		contractLevel:"Contract level",
		DailyInnings:"Contract number of games per day",
		today:"Number of games played today",
		maturity:"Contract expiration date",
		minersReward:"The incentive coefficient of miners' expenses",
		lockUp:"Contract lock up",
		lockUpNum:'Get more games',
		rule:"Contract rules",
		lowNum:"Low multiples",
		heightNum:"high-expansion",
		rising:"rising pouring",
		risingTitle:"Fixed bets developed throughout the day",
		risingTitle2:"Time limit open optional multiple",
		matching:"matching",
	},
	JapanLanguage:{
		earned:"獲得した累積",
		income:'已获得收益累计',
		rewards:'クリックしてプロモーション特典を表示',
		time:"時間",
		amount:"量",
		lock:'閉じ込める',
		confirmBinding:"バインドを確認",
		contractPeriod:'契約サイクル',
		day:"日",
		everyday:'毎日のゲーム盤プレゼント:',
		contractNum:'局',
		getCode:'招待コードを入力してください',
		addBind:'バインディングを追加',
		sendCode:"招待コードを入力してください",
		unbind:"解放する",
		bound:"バウンド",
		yCommunity:"私のコミュニティ",
		myCommunity:"私のコミュニティ",
		accumulated:"蓄積されたチケットフィードバック",
		people:"人",
		choose:"選んでください",
		
		minersReward:"鉱員費奨励係数",
		gameDe:'ゲームボタン',
		deductions:'引き落としタイプ',
		code:"招待コード",
		Invite:"招待関係",
		community:'私のコミュニティー',
		reward:"普及奨励",
		copy:"ふくせい ",
		cumulative:"獲得した報酬は累積する",
		feedback:"チケットのフィードバック累計を獲得した",
		withhold:"入場料引き落とし",
		backgd:"背景音楽",
		contractLevel:"契約等級",
		DailyInnings:"契約日ゲーム局数プレゼント",
		today:"今日は遊んだ",
		maturity:"契約期間",
		lockUp:"契約くら",
		lockUpNum:'ゲームの回数を増やす',
		rule:"契約規則",
		lowNum:"低倍数",
		heightNum:"高い倍数",
		rising:"底注",
		risingTitle:"固定投与を終日開放した",
		risingTitle2:"オプションの倍数を期間限定で開放する",
		matching:"即時マッチング",
	},
	KoreanLanguage:{
		earned:"누적 누적",
		rewards:'프로모션 보상을 보려면 클릭하십시오',
		 time:"시각",
		 amount:"양",
		 lock:'자물쇠',
		 choose:"초이스해주세요.",
		 confirmBinding:"바인딩 확인",
		 contractPeriod:'계약주기',
		 day:"일",
		 everyday:'매일 게임 보드 선물:',
		 contractNum:'국',
		 getCode:"초대 코드를 입력하십시오",
		 addBind:'바인딩 추가',
		 sendCode:"초대 코드를 입력하십시오",
		 unbind:"바인드 해제",
		 bound:"경계",
		 yCommunity:"내 커뮤니티",
		 myCommunity:"我的社群",
		 accumulated:"내 커뮤니티",
		 minersReward:"광부 비용 장려 계수",
		 gameDe:'게임 비용 공제',
		 deductions:'공제 유형',
		 code:"초대장 번호",
		 Invite:"초청 관계",
		 community:'저의 지역사회는',
		 reward:"장려를 확대하다.",
		 copy:"복사",
		 cumulative:"누계된 수익",
		 feedback:"이미 입장권 피드백 루계를 얻다",
		 withhold:"입장료 공제",
		 backgd:"배경 음악",
		 contractLevel:"계약 단계",
		 DailyInnings:"게임 데스크 게임 제공",
		 today:"오늘은 이미 게임 수를 두었다.",
		 maturity:"계약 만료 시간",
		 lockUp:"계약이 파쇄되다",
		 lockUpNum:'더 많은 게임 가져오기',
		 rule:"계약 규칙",
		 lowNum:"저배수",
		 heightNum:"고배수",
		 rising:"바닥이 주해",
		 risingTitle:"오픈 퍼팅",
		 risingTitle2:"선택할 수 있는 배수를 한시적으로 개방하다",
		 matching:"지금 일치",
		 people:"사람이",
	},
}