export default {
	ChinaLanguage: {
		informationempty:'信息不能为空',
		thereOpenContract:'有未过期的合约',
		undo:'撤销',
		notYetOpen:'暂未开放',
		lock:'锁仓',
		contractPeriod:'合约周期',
		day:"天",
		everyday:'每日游戏局属赠予:',
		contractNum:'局',
		yesterdaycoefficient:'昨日已玩局数',
		dataTime:'时间',
		cancelOrder:'是否撤销',
		rechargeAmount:'充值金额',
		placeRechargeAmount:'请输入充值金额',
		withdrawalAmount:'提现金额',
		PleaseWithdrawalAmount:'请填写提现金额',
		available:'可获得',
		currentExchangeRate:'当前汇率',
		noData:'暂无数据',
		details:'查看详情',
		bureau:'局',
		communitylevel:'社群等级',
		level:'等级',
		directPush:'我的直推人数',
		myDirectUserRecord:'我的直推用户记录',
		myDirectRecord:'我的直推记录',
		processing: '进行中',
		revoked: '已撤销',
		sell: '卖出',
		buyIn: '买入',
		yesterdaycoefficient: '昨日已玩局数',
		dataTime: '时间',
		cancelOrder: '是否撤销',
		rechargeAmount: '充值金额',
		placeRechargeAmount: '请输入充值金额',
		withdrawalAmount: '提现金额',
		PleaseWithdrawalAmount: '请填写提现金额',
		available: '可获得',
		currentExchangeRate: '当前汇率',
		game: '游戏',
		officialAnnouncement: '官方公告',
		accountAssets: '账户资产',
		recharge: '充值',
		withdrawal: '提现',
		orePool: '矿池',
		DisneyTheLionKing: '狮子王',
		newsFlash: '快讯',
		availableBalance: '可用余额',
		frozenBalance: '冻结余额',
		totalBalance: '总余额',
		assetRecords: '资产记录',
		currency: '币类',
		transferAddress: '转账地址',
		amountOfMoney: '金额',
		selectCurrency: '选择币种',
		pleaseSelectCurrency: '请选择币种',
		PleaseFillInTheTransferAmount: '请填写转账金额',
		notes: '备注',
		optional: '选填',
		gameAssetBalance: '游戏资产余额',
		minersExpenses: '矿工费用',
		nextStep: '下一步',
		pleaseInputPassword: '请输入密码',
		determine: '确定',
		cancel: '取消',
		whole: '全部',
		cumulativeRelease: '已累计释放',
		minePoolBalance: '矿池余额',
		releaseCoefficient: '释放系数',
		releaseRecord: '释放记录',
		noRecord: '暂无记录',
		withdrawalOfAssets: '资产提现',
		lionKingDividendWeighted: '狮子王分红加权',
		contract: '合约',
		test1: '永久加权分红40%游戏矿工费',
		test2: '名额仅剩',
		name: '名',
		buyNow: '立即抢购',
		promotionReward: '推广奖励',
		communityPromotionAward: '社区推广奖励',
		promotionOfIncentiveRules: '推广激励规则',
		communityLevel: '社区等级',
		gamesCompletedToday: '今日已玩局数',
		communityDividendCoefficient: '社区分红系数',
		accumulatedCommunityDividendsObtained: '已获得社区分红累计',
		yesterdayCommunityBonusAccumulated: '昨日获得社区分红累计',
		communityPromotionIncentiveRecord: '社区推广激励记录',
		listOfCommunityPromotionIncentives: '社区推广激励排行榜',
		individualPromotionAward: '个人推广奖励',
		myPushRecord: '我的直推记录',
		usersHaveBeenPromotedDirectly: '已直接推广用户',
		indirectlyPromotedUsers: '已间接推广用户',
		accumulatedIndividualPromotionAwards: '已获得个人推广奖励累计',
		numberOfGamesDirectlyPromotedToday: '今日已直接推广游戏局数',
		numberOfGamesPromotedIndirectlyToday: '今日已间接推广游戏局数',
		personalPromotionIncentiveRecord: '个人推广激励记录',
		personalPromotionIncentiveRanking: '个人推广激励排行榜',
		shareMyPromotionAchievements: '分享我的推广战绩',
		inviteMoreFriends: '邀请更多好友',
		shareNow: '立即分享',
		communityPromotionIncentive: '社区推广激励',
		test3: '系统获取拿出',
		test4: '用于激励用户推广',
		test5: '个人奖励+团队奖励（全平台）10元中的',
		test6: '团队奖励（例如:A1中奖，10元中的30%按照网体等级分给其他9人）',
		test7: '每日12点结算前一日的数据',
		personalPromotionIncentive: '个人推广激励',
		test8: '直推，推广用户每玩一局获得0.2价值的TLK',
		test9: '间推，推广用户每玩一局获得0.1价值的TLK',
		time: '时间',
		number: '数量',
		noDataAvailable: '暂无数据',
		user: '用户',
		cumulativeTlkQuantity: '累计TLK数量',
		cumulativeCubQuantity: '累计CUB数量',
		myDirectPushUserRecord: '我的直推用户记录',
		myNumberOfDirectTweets: '我的直推人数',
		saveToAlbum: '保存至相册',
		mine: '我的',
		CreateTheWorldMe: '创世人',
		securitySetting: '安全设置',
		aboutUs: '关于我们',
		messageCenter: '消息中心',
		feedBack: '意见反馈',
		exportWordMe: '导出助记词',
		exportPrivateKeyMe: '导出私钥',
		updatePwd: '修改密码',
		confirmPwd: '确认',
		cancelPwd: '取消',
		pleasetakeGoodKey: '请妥善保管您的助记词',
		saveToAlbumKey: '保存至相册',
		exportKeyTip: ' 请妥善保管私钥，建议离线保存，屋里隔绝，远离网络请勿在私钥联网的情况下分享储存，避免丢失，一旦被人恶意获取，可能造成不可挽回的资产损失 ',
		copyPrivateKey: '复制私钥',
		enterOldPwd: '输入旧密码',
		placeEnterOldPwd: '请输入旧密码',
		enterNewPwd: '输入新密码',
		placeEnterNewPwd: '请输入新密码',
		confirmNewPwd: '确认新密码',
		placeConfirmNewPwd: '请确认新密码',
		confirmChange: '确认修改',
		placeFeedBack: '请告诉我们您遇到的问题或想反馈的意见',
		submitFeedBack: '提交',
		collectionWalletAddress: '收款钱包地址',
		collectionWalletAddressPh: '请输入收款钱包地址',
		inputTransferAmount: '请输入转账金额',
		transferAmountRemark: '请填写转账备注',
		ServiceChargeTrans: '手续费',
		allMoney: '全部',
		addWalletAddress: '新建钱包地址',
		walletAddressType: '地址类型',
		walletAddress: '地址',
		ValidAddress: '请输入有效地址',
		walletName: '名称',
		validName: '请输入名称',
		preservationAddress: '保存',
		collectionTron: '该地址仅支持TRON转账收款，请勿用于其他币种',
		copyCollectionAddress: '复制收款地址',
		indexOfficialAnnouncement: '官方公告',
		MyAssets: '我的资产',
		transferAmountIndex: '转账',
		collectionIndex: '收款',
		makeMoney: '邀请好友一起赚钱',
		erweima: '邀请码',
		saomiao: '扫描注册并下载APP',
		lowPowerField: '低倍场',
		bottomNote: '底注',
		test10: '全天开放 固定投注',
		test11: '限时开放 可选倍数',
		highPowerField: '高倍场',
		leaveYourSeat: '离开座位',
		keepPlaying: '继续游戏',
		test12: '不玩了,休息一下',
		nickname: '昵称',
		accountID: '账户ID',
		totalGamesPlayed: '已玩游戏局数总计',
		winningAuctionRate: '获得竞拍率',
		numberOfGamesAvailableToday: '今日游戏可玩局数',
		contractGrade: '合约等级',
		contractDailyGameNumberGift: '合约每日游戏局数赠与',
		contractExpirationTime: '合约到期时间',
		test13: '合约锁仓TLK，获取更多游戏次数',
		contractRules: '合约规则',
		test14: `1.新注册用户可体验试玩一局
		2.用户需进行合约锁仓才能玩游戏，锁仓不同的金额，对应不同的合约等级，每个等级每天游戏赠予局数游戏局数和合约的有效天数都不相同。
		3.
		V0(锁仓11JDT，合约周期1天，每日游戏局属赠予:10局)
		V1(锁仓200JDT，合约周期7天，每日游戏局属赠予:50局)
		V2(锁仓1648JDT，合约周期30天，每日游戏局属赠予:100局)
		V3(锁仓4230JDT，合约周期60天，每日游戏局属赠予:200局)
		V4(锁仓8248JDT，合约周期90天，每日游戏局属赠予:400局) 
		V5(锁仓21015JDT，合约周期180天，每日游戏局属赠予:500局)`,
		lockUpAmount: '锁仓金额',
		lockUp: '确定锁仓',
		lockUpRecord: '锁仓记录',
		lockTime: '锁仓时间',
		myInvitationCode: '我的邀请码',
		copy: '复制',
		invitationRelationship: '邀请关系',
		test15: '点击查看推广奖励',
		accumulatedIncome: '已获得收益累计',
		test16: '已获得门票反馈累计',
		type: '类型',
		ticketRebate: '门票扣款',
		stake: '扣款类型',
		reward: '游戏扣款',
		bgm: '背景音乐',
		successfulAuction: '竞拍成功',
		congratulations: '恭喜',
		prizeSettlement: '奖品结算',
		myPrize: '我的奖品',
		otherPrizes: '其余奖品',
		oldPwdNull: '旧密码不能为空',
		newPwdNull: '新密码不能为空',
		confirmPwdNull: '确认密码不能为空',
		twoPwdAtypism: '两次密码不一致',
		blockchainBrowserView: '前往区块链浏览器查看',
		editAddressWallet: '编辑地址',
		addressNull: '地址为必填项',
		addressFormat: '地址格式不正确',
		nameNull: '名称为必填项',
		tronTransfer: 'TRON转账',
		currencyAccountNull: '币种为必填项',
		walletAddressNull: '钱包地址为必填项',
		transferAccountNull: '转账金额为必填项',
		transferAmountCannotBalance: '转账金额不能大于余额',
		availableBalance: '可用余额为',
		tronTransferCollection: 'TRON转账收款',
		selectTransferAddress: '选择收款钱包地址',
		elephant: '小象',
		leopard: '小豹',
		wolf: '小狼',
		tiger: '小虎',
		reminder: '温馨提示',
		YourContractExpire: '您的合约即将到期',
		CreateWalletGuidPage: '创建钱包引导页',
		pleaseOpenWallet: '请开启您的第一个数字钱包',
		createWallet: '创建钱包',
		importWallet: '导入钱包',
		created1: '选择低层公链',
		testFail: "验证失败",

		createdWallet: '创建钱包',
		walletName: '钱包名称',
		walletName_value: '请输入钱包名称',
		walletErr_value1: "钱包名称为必填项",
		walletErr_value2: "不能少于3个字符",
		walletErr_value3: "存在非法字符",
		walletErr_value4: "名称不能多于15个字符",

		setPassWord: '设置密码',
		setPassWord_value: "请输入新密码",
		PassWordErr_value1: "密码为必填项",
		PassWordErr_value2: "不能少于6个字符",
		PassWordErr_value3: "密码必须带英文数字！",
		PassWordErr_value4: "密码不能多于15个字符！",
		PassWordErr_value5: "两次密码不一致！",

		confirmPassWord: '再次输入密码',
		confirmPassWord_value: "请再次输入密码",
		showToast: '请完善资料',

		backup: '备份提示',
		backupTitle: "备忘助记词",
		backupTaps: "温馨提示",
		backupValue: '获得助记词等于拥有钱包资产所有权',
		backupListVal: [{
				txt: '助记词由英文单词组成，请抄写并妥善保管',
			},
			{
				txt: '助记词丢失，无法找回，请务必备份好',
			},
			{
				txt: "请勿截屏分享或电子设备储存，这可能遭到第三方恶意采集，造成资产损失"
			}
		],

		backups:'备份助记词',
		backupsVal:"按照顺序备份助记词",
		
		testBackups:'验证备份',
		testBackupsVal:"按照顺序点击下方助记词，已确认您正确备份",
		
		importWallet:'导入钱包',
		words:'助记词',
		wordsTitle:"请按照顺序输入助记词，使用助记词导入钱包的同时 可以重置密码",
		wordsErrVal:'助记词为必填项',
		wordsVal:'请输入助记词，并使用英文逗号分隔',
		secretKey:'私钥',
		secretKeyErrVal:"私钥为必填项",
		secretKeyTitle:"复制粘贴波场官方钱包PrivateKey件内容至输入框或通过扫描Private Key内容生成的二维码导入，请留意大小写",
		secretKeyVal:"请输入私钥",
		secretKeyNext:'开始导入',
		contractCopy:"1.用户需进行合约锁仓才能玩游戏，锁仓不同的金额，对应不同的合约等级，每个等级每天游戏赠予局数游戏局数和合约的有效天数都不相同。",
		addWallet:'添加钱包',
		importWallet:"导入钱包",

		backups: '备份助记词',
		backupsVal: "按照顺序备份助记词",

		testBackups: '验证备份',
		testBackupsVal: "按照顺序点击下方助记词，已确认您正确备份",

		importWallet: '导入钱包',
		words: '助记词',
		wordsTitle: "请按照顺序输入助记词，使用助记词导入钱包的同时 可以重置密码",
		wordsErrVal: '助记词为必填项',
		wordsVal: '请输入助记词，并使用英文逗号分隔',
		secretKey: '私钥',
		secretKeyErrVal: "私钥为必填项",
		secretKeyTitle: "复制粘贴波场官方钱包PrivateKey件内容至输入框或通过扫描Private Key内容生成的二维码导入，请留意大小写",
		secretKeyVal: "请输入私钥",
		secretKeyNext: '开始导入',

		addWallet: '添加钱包',
		importWallet: "导入钱包",

		more: "更多",
		moreLists: [
			{
				icon: 'url(/static/index/more1.png)',
				cTitle: '白皮书',
				title: 'WHITE PAPER',
			},
			{
				icon: 'url(/static/index/more2.png)',
				cTitle: '项目介绍',
				title: 'Project introduction',
			},
			{
				icon: 'url(/static/index/more3.png)',
				cTitle: '视频链接',
				title: 'Video link',
			},
			{
				icon: 'url(/static/index/more4.png)',
				cTitle: '交易所',
				title: 'exchange',
				lists: [{
						address: 'zhongbi',
						url: "https://www.zb.live/cn/"
					},
					{
						address: 'huobi',
						url: "https://www.huobi.me"
					},
					{
						icon:'url(/static/index/more4.png)',
						cTitle:'交易所',
						title:'exchange',
						lists:[
							{
								address:'中币',
								url:"https://www.zb.live/cn/"
							},
							{
								address:'火币',
								url:"https://www.huobi.me"
							},
							{
								address:'coinbase',
								url:"https://www.coinbase.com/"
							},
							{
								address:'okex',
								url:"https://www.okex.me"
							}
						],
						address: 'coinbase',
						url: "https://www.coinbase.com/"
					},
					{
						address: 'okex',
						url: "https://www.okex.me"
					}
				]
			},
			{
				icon: 'url(/static/index/more5.png)',
				cTitle: '生态建设',
				title: 'Ecological construction',
			}
		],

		notice: "官方公告",
		news: '快讯',

		checkoutWallet: '切换钱包',

		transaction: '交易',
		assets: '账户资产',
		transactionTaps1: '交易市场',
		transactionTaps2: "订单记录",
		transactionTitle: '资产明细',
		transactionListVal1: '可用余额',
		transactionListVal2: '冻结余额',
		transactionListVal3: '矿池余额',
		transactionTotal: "总余额",

		market: '交易市场',
		marketTaps: '查看市场行情',
		marketBuy: '买入',
		marketSell: "卖出",
		marketLeftTaps1: '五档',
		marketLeftTaps2: '明细',
		fiveTitle1: "盘口",
		fiveTitle2: "价格",
		fiveTitle3: "数量",
		fiveTitle4: "时间",
		fiveTitle4: "最新成交",
		marketRightTaps1: "限价",
		marketRightTaps2: "市价",
		marketR_Title1: "价格",
		marketR_Title1Low: "市场价",
		marketR_Title2: "数量",
		marketR_Title2Val: "请输入数量",
		marketR_Ava1: "可用",
		marketR_Ava2: "全部",
		marketR_BottomVal: "交易额",

		market_24hTop: "24小时最高",
		market_24hLow: "24小时最低",
		market_24hDeal: '24小时成交量',
		marketDetailsVal1: '深度',
		marketDetailsVal2: '成交',
		marketListTitle1: '买盘数量',
		marketListTitle2: '价格',
		marketListTitle3: '卖盘数量',
		marketListTitle4: '时间',
		marketListTitle5: '方向',
		marketListTitle6: '数量',

		order: '订单记录',
		orderTaps1: "委托记录",
		orderTaps2: "成交记录",
		orderListVal1: "限价单",
		orderListVal2: "已完成",
		orderListVal3: "已撤销",
		orderListVal4: "市价单",
		orderListVal5: "成交均价",
		orderListVal6: "已成交",
		orderListVal7: "成交总额",
		orderListVal8: "手续费",
		orderListVal9: '成交金额',
		nextComplete: '完成',
		inDev: '敬请期待！'
	},
	EnglisghLanguage: {
		informationempty:'Information cannot be empty',
		thereOpenContract:'There are unexpired contracts',
		undo:'Undo',
		notYetOpen:'Not yet open',
		lock:'Lock up',
		contractPeriod:'Contract period',
		day:"day",
		everyday:'Daily game board gift:',
		contractNum:'games',
		yesterdaycoefficient:"Number of games played yesterday",
		dataTime:'time',
		cancelOrder:'Whether to cancel',
		rechargeAmount:'Recharge Amount',
		placeRechargeAmount:'Please enter the recharge amount',
		withdrawalAmount:'Withdrawal Amount',
		PleaseWithdrawalAmount:'Please fill in the cash withdrawal amount',
		available:'Available',
		currentExchangeRate:'Current exchange rate',
		noData:'No data',
		details:'details',
		bureau:'Bureau',
		communitylevel:'Community level',
		level:'grade',
		directPush:'Direct push',
		myDirectUserRecord:'My Direct User Record',
		myDirectRecord:'My direct record',
		revoked:'Revoked',
		processing: 'processing',
		sell: 'Sell',
		buyIn: 'Buy in',
		yesterdaycoefficient: "Number of games played yesterday",
		dataTime: 'time',
		cancelOrder: 'Whether to cancel',
		rechargeAmount: 'Recharge Amount',
		placeRechargeAmount: 'Please enter the recharge amount',
		withdrawalAmount: 'Withdrawal Amount',
		PleaseWithdrawalAmount: 'Please fill in the cash withdrawal amount',
		available: 'Available',
		currentExchangeRate: 'Current exchange rate',
		game: 'Game',
		officialAnnouncement: 'Official announcement',
		accountAssets: 'Account assets',
		recharge: 'Recharge',
		withdrawal: 'Withdrawal',
		orePool: 'MinePool',
		DisneyTheLionKing: 'The Lion King',
		newsFlash: 'Quick news',
		availableBalance: 'Available balance',
		frozenBalance: 'Frozen balance',
		totalBalance: 'Total balance',
		assetRecords: 'asset records',
		currency: 'Currency',
		transferAddress: 'transfer address',
		amountOfMoney: 'Amount',
		selectCurrency: 'Select currency',
		pleaseSelectCurrency: 'Please select currency',
		PleaseFillInTheTransferAmount: 'Please fill in the transfer amount',
		notes: 'Remarks',
		optional: 'Optional',
		gameAssetBalance: 'Game asset balance',
		minersExpenses: 'Miner Expenses',
		nextStep: 'Next',
		pleaseInputPassword: 'Please enter the password',
		determine: 'OK',
		cancel: 'Cancel',
		whole: 'All',
		cumulativeRelease: 'Accumulated release',
		minePoolBalance: 'Mining pool balance',
		releaseCoefficient: 'Release coefficient',
		releaseRecord: 'Release record',
		noRecord: 'No record yet',
		withdrawalOfAssets: 'Asset withdrawals',
		lionKingDividendWeighted: 'Lion King Dividend Weighted',
		contract: 'Contract',
		test1: 'Permanently weighted dividend 40% game miner fee',
		test2: 'Only the quota is left',
		name: 'Name',
		buyNow: 'Purchase Now',
		promotionReward: 'Promotion Reward',
		communityPromotionAward: 'Community Promotion Award',
		promotionOfIncentiveRules: 'Promotion incentive rules',
		communityLevel: 'Community level',
		gamesCompletedToday: 'Today completed games',
		communityDividendCoefficient: 'Community Dividend Coefficient',
		accumulatedCommunityDividendsObtained: 'Accumulated community dividends',
		yesterdayCommunityBonusAccumulated: 'Accumulated community dividends yesterday',
		communityPromotionIncentiveRecord: 'Community Promotion Incentive Record',
		listOfCommunityPromotionIncentives: 'Community Promotion Incentive Leaderboard',
		individualPromotionAward: 'Individual Promotion Award',
		myPushRecord: 'My direct push record',
		usersHaveBeenPromotedDirectly: 'Users have been promoted directly',
		indirectlyPromotedUsers: 'Indirectly promoted users',
		accumulatedIndividualPromotionAwards: 'Accumulated individual promotion rewards',
		numberOfGamesDirectlyPromotedToday: 'Today has directly promoted the number of game rounds',
		numberOfGamesPromotedIndirectlyToday: 'Today has indirectly promoted the number of game rounds',
		personalPromotionIncentiveRecord: 'Personal Promotion Incentive Record',
		personalPromotionIncentiveRanking: 'Personal Promotion Incentive Leaderboard',
		shareMyPromotionAchievements: 'Share my promotion record',
		inviteMoreFriends: 'Invite more friends',
		shareNow: 'Share Now',
		communityPromotionIncentive: 'Community Promotion Incentive',
		test3: 'System gets out',
		test4: 'Used to encourage user promotion',
		test5: 'Individual reward + team reward (all platforms) in 10 yuan',
		test6: 'Team rewards (for example: A1 winning, 30% of the 10 yuan will be distributed to other 9 people according to the net level)',
		test7: 'Data of the day before settlement at 12 clock every day',
		personalPromotionIncentive: 'Personal Promotion Incentive',
		test8: 'direct push, promote users to get 0.2 TLK for every game played',
		test9: 'Introduce, promote users to get 0.1 value of TLK per game',
		time: 'time',
		number: 'number',
		noDataAvailable: 'No data available',
		user: 'User',
		cumulativeCubQuantity: 'cumulative CUB quantity',
		cumulativeTlkQuantity: 'cumulative TLK quantity',
		myDirectPushUserRecord: 'My direct push user record',
		myNumberOfDirectTweets: 'My direct push number',
		saveToAlbum: 'Save to Album',
		makeMoney: 'Invite friends to make money together',
		erweima: 'Invitation code',
		saomiao: 'Scan to register and download APP',
		lowPowerField: 'Low power field',
		bottomNote: 'Bottom note',
		test10: 'Open all day fixed betting',
		test11: 'Open time limit optional multiple',
		highPowerField: 'High power field',
		leaveYourSeat: 'Leave seat',
		keepPlaying: 'Continue to play',
		test12: 'No more playing, take a break',
		nickname: 'nickname',
		accountID: 'Account ID',
		totalGamesPlayed: 'Total number of games played',
		winningAuctionRate: 'Get auction rate',
		numberOfGamesAvailableToday: 'Today game playable number of games',
		contractGrade: 'Contract grade',
		contractDailyGameNumberGift: 'Contract daily game rounds gift',
		contractExpirationTime: 'Contract expiration time',
		test13: 'Contract lock TLK, get more game times',
		contractRules: 'Contract Rules',
		test14: `1. Newly registered users can experience a trial game 
				 2. Users need to lock the contract to play the game, different amounts of lockup correspond to different contract levels, each level of the game is given to the number of games per day It is different from the effective days of the contract.
				  3. 
				  V0 (locked position 11JDT, contract period of 1 day, daily game board is a gift: 10 rounds) 
				  V1 (locked position 200JDT, contract period of 7 days, daily game board is a gift: 50 rounds)
				   V2 (locked position 1648JDT, contract period 30 days, daily game board grant: 100 rounds) 
				   V3 (locked position 4230JDT, contract period 60 days, daily game board grant: 200 rounds) 
				   V4 (locked position 8248JDT, contract period 90 days , Daily game board gift: 400 rounds) 
				   V5 (locked position 21015JDT, contract period 180 days, daily game board gift: 500 rounds)`,
		lockUpAmount: 'Lock position amount',
		lockUp: 'determine lock position',
		lockUpRecord: 'Lock warehouse record',
		lockTime: 'Lock position time',
		myInvitationCode: 'My invitation code',
		copy: 'copy',
		invitationRelationship: 'Invitation relationship',
		test15: 'Click to view promotion rewards',
		accumulatedIncome: 'Accumulated gains',
		test16: 'Accumulated ticket feedback has been obtained',
		type: 'type',
		ticketRebate: 'Ticket deduction',
		stake: 'Deduction type',
		reward: 'Game deduction',
		bgm: 'Background music',
		successfulAuction: 'Auction success',
		congratulations: 'Congratulations',
		prizeSettlement: 'Prize settlement',
		myPrize: 'My prize',
		otherPrizes: 'Remaining prizes',
		mine: 'mine',
		CreateTheWorldMe: 'Creative World',
		securitySetting: 'Security settings',
		aboutUs: 'About us',
		messageCenter: 'Message Center',
		feedBack: 'Feedback',
		exportWordMe: 'Export mnemonic words',
		exportPrivateKeyMe: 'Export private key',
		updatePwd: 'Change password',
		confirmPwd: 'Confirm',
		cancelPwd: 'Cancel',
		pleasetakeGoodKey: 'Please take good care of your mnemonic words',
		saveToAlbumKey: 'Save to Album',
		exportKeyTip: 'Please keep the private key properly, it is recommended to keep it offline, isolated in the house, away from the network, please do not share the storage when the private key is connected to the network, to avoid loss, once it is maliciously acquired by someone, it may cause irreparable asset losses',
		copyPrivateKey: 'Copy private key',
		enterOldPwd: 'Enter old password',
		placeEnterOldPwd: 'Please enter the old password',
		enterNewPwd: 'Enter new password',
		placeEnterNewPwd: 'Please enter a new password',
		confirmNewPwd: 'Confirm new password',
		placeConfirmNewPwd: 'Please confirm the new password',
		confirmChange: 'Confirm change',
		placeFeedBack: 'Please tell us your problems or comments you want to feedback',
		submitFeedBack: 'Submit',
		collectionWalletAddress: 'Receipt wallet address',
		collectionWalletAddressPh: 'Please enter the collection wallet address',
		inputTransferAmount: 'Please enter the transfer amount',
		transferAmountRemark: 'Please fill in the transfer remarks',
		ServiceChargeTrans: 'Handling fee',
		allMoney: 'All',
		addWalletAddress: 'New wallet address',
		walletAddressType: 'Address type',
		walletAddress: 'Address',
		ValidAddress: 'Please enter a valid address',
		walletName: 'Name',
		validName: 'Please enter a name',
		preservationAddress: 'Save',
		collectionTron: 'This address only supports TRON transfer payment, please do not use it in other currencies',
		copyCollectionAddress: 'Copy collection address',
		indexOfficialAnnouncement: 'Official Announcement',
		MyAssets: 'My assets',
		transferAmountIndex: 'Transfer',
		collectionIndex: 'Receipt',
		oldPwdNull: 'Old password cannot be empty',
		newPwdNull: 'The new password cannot be empty',
		confirmPwdNull: 'Confirm password cannot be empty',
		twoPwdAtypism: 'Two passwords are inconsistent',
		blockchainBrowserView: 'Go to the blockchain browser to view',
		editAddressWallet: 'Edit address',
		addressNull: 'Address is required',
		addressFormat: 'Address format is incorrect',
		nameNull: 'Name is required',
		tronTransfer: 'TRON transfer',
		currencyAccountNull: 'Currency is required',
		walletAddressNull: 'Wallet address is required',
		transferAccountNull: 'The transfer amount is required',
		transferAmountCannotBalance: 'The transfer amount cannot be greater than the balance',
		availableBalance: 'Available balance is',
		tronTransferCollection: 'TRON transfer payment',
		selectTransferAddress: 'Select the payment wallet address',
		elephant: 'Elephant',
		leopard: 'Leopard',
		wolf: 'Wolf',
		tiger: 'Tiger',
		reminder:'Warm reminder',
		YourContractExpire:'Your contract is about to expire',
		CreateWalletGuidPage:'Create wallet guide page',
		pleaseOpenWallet:'Please open your first digital wallet',
		createWallet:'Create wallet',
		importWallet:'Import Wallet',
		created1:'Select low-level public chain',
		testFail:'failure',
		contractCopy:'Users need to lock the contract to play the game. Different amounts of lockups correspond to different contract levels. Each level of the game is given to the number of games per day. The number of games and the number of days of the contract are different.',
		
		createdWallet:'Create wallet',
		walletName:'Wallet name',
		walletName_value:'Please enter the wallet name',
		reminder: 'Warm reminder',
		YourContractExpire: 'Your contract is about to expire',
		CreateWalletGuidPage: 'Create wallet guide page',
		pleaseOpenWallet: 'Please open your first digital wallet',
		createWallet: 'Create wallet',
		importWallet: 'Import Wallet',
		created1: 'Select low-level public chain',
		testFail: 'failure',

		createdWallet: 'Create wallet',
		walletName: 'Wallet name',
		walletName_value: 'Please enter the wallet name',
		walletErr_value1: "Wallet name is required",
		walletErr_value2: "Not less than 3 characters",
		walletErr_value3: "Illegal character exists",
		walletErr_value4: "The name cannot exceed 15 characters",

		setPassWord: 'Set password',
		setPassWord_value: "Please enter a new password",
		PassWordErr_value1: "Password is required",
		PassWordErr_value2: "Not less than 6 characters",
		PassWordErr_value3: "Password must have English numbers!",
		PassWordErr_value4: "Password cannot exceed 15 characters!",
		PassWordErr_value5: "Two passwords are inconsistent!",

		confirmPassWord: 'Enter the password again',
		confirmPassWord_value: "Please enter the password again",
		showToast: 'Please complete the information',

		backup: 'Backup prompt',
		backupTitle: "Memo mnemonic",
		backupTaps: "Warm Tips",
		backupValue: 'Obtaining mnemonic words equals ownership of wallet assets',
		backupListVal: [{
				txt: 'The mnemonic is composed of English words, please copy and keep it properly',
			},
			{
				txt: 'The mnemonic is missing and cannot be retrieved, please make sure to back it up',
			},
			{
				txt: "Do not share screenshots or store on electronic devices, this may be maliciously collected by a third party, causing asset loss"
			}
		],

		lock:'Lock up',
		contractPeriod:"Contract cycle",
		day:'day',
		everyday:"Daily game board gift",
		contractNum:"Bureau",
		
		backups:'Backup mnemonic words',


		backups: 'Backup mnemonic words',
		backupsVal: "Backup mnemonic words in order",

		testBackups: 'Verify backup',
		testBackupsVal: "Click the mnemonic words in order, you have confirmed that you backed up correctly",

		importWallet: 'Import wallet',
		words: 'mnemonic words',
		wordsTitle: "Please enter the mnemonic words in order, and you can reset the password while importing the wallet using the mnemonic words",
		wordsErrVal: 'mnemonic words are required',
		wordsVal: 'Please enter mnemonic words, separated by commas',
		secretKey: 'Private key',
		secretKeyErrVal: "Private key is required",
		secretKeyTitle: "Copy and paste the content of PrivateKey of TRON official wallet into the input box or import the QR code generated by scanning the content of Private Key, please pay attention to capitalization",
		secretKeyVal: "Please enter the private key",
		secretKeyNext: 'Start import',

		more: "More",
		moreLists: [{
				icon: 'url(/static/index/more1.png)',
				cTitle: 'White Paper',
				title: 'WHITE PAPER',
			},
			{
				icon: 'url(/static/index/more2.png)',
				cTitle: 'Project Introduction',
				title: 'Project introduction',
			},
			{
				icon: 'url(/static/index/more3.png)',
				cTitle: 'Video link',
				title: 'Video link',
			},
			{
				icon: 'url(/static/index/more4.png)',
				cTitle: 'Exchange',
				title: 'exchange',
				lists: [{
						address: 'zhongbi',
						url: "https://www.zb.live/cn/"
					},
					{
						address: 'huobi',
						url: "https://www.huobi.me"
					},
					{
						address: 'coinbase',
						url: "https://www.coinbase.com/"
					},
					{
						address: 'okex',
						url: "https://www.okex.me"
					}
				]
			},
			{
				icon: 'url(/static/index/more5.png)',
				cTitle: 'Ecological Construction',
				title: 'Ecological construction',
			}
		],

		notice: "Official announcement",
		news: 'Express News',

		checkoutWallet: 'Switch wallet',

		transaction: 'Transaction',
		assets: 'Account assets',
		transactionTaps1: 'Transaction Market',
		transactionTaps2: "Order record",
		transactionTitle: 'Asset Details',
		transactionListVal1: 'Available balance',
		transactionListVal2: 'Freeze balance',
		transactionListVal3: 'Mining pool balance',
		transactionTotal: "Total balance",

		market: 'Trading market',
		marketTaps: 'View market conditions',
		marketBuy: 'Buy',
		marketSell: "Sell",
		marketLeftTaps1: 'Five gears',
		marketLeftTaps2: 'Details',
		fiveTitle1: "Handicap",
		fiveTitle2: "Price",
		fiveTitle3: "Quantity",
		fiveTitle4: "Time",
		fiveTitle4: "Latest Deal",
		marketRightTaps1: "Limit Price",
		marketRightTaps2: "Market Price",
		marketR_Title1: "Price",
		marketR_Title1Low: "Market Price",
		marketR_Title2: "Quantity",
		marketR_Title2Val: "Please enter the quantity",
		marketR_Ava1: "Available",
		marketR_Ava2: "All",
		marketR_BottomVal: "Transaction Amount",

		market_24hTop: "Highest in 24 hours",
		market_24hLow: "24-hour minimum",
		market_24hDeal: '24-hour volume',
		marketDetailsVal1: 'Depth',
		marketDetailsVal2: 'Deal',
		marketListTitle1: 'Number of buying orders',
		marketListTitle2: 'price',
		marketListTitle3: 'Number of sells',
		marketListTitle4: 'Time',
		marketListTitle5: 'Direction',
		marketListTitle6: 'Quantity',

		order: 'Order record',
		orderTaps1: "Delegated Record",
		orderTaps2: "Deal Record",
		orderListVal1: "Limit order",
		orderListVal2: "Completed",
		orderListVal3: "Withdrawn",
		orderListVal4: "Market Order",
		orderListVal5: "Average price",
		orderListVal6: "Dealed",
		orderListVal7: "Total Transaction",
		orderListVal8: "Handling Fee",
		orderListVal9: 'Transaction amount',
		nextComplete: 'Complete',
		inDev: 'Stay tuned！',

		addWallet: 'Add wallet',
		importWallet: "Import wallet",
	},
	JapanLanguage: {
		informationempty:'情報を空にすることはできません',
		thereOpenContract:'期限が切れていない契約があります',
		undo:'元に戻す',
		notYetOpen:'まだ開いていません',
		lock:'閉じ込める',
		contractPeriod:'契約サイクル',
		day:"日",
		everyday:'毎日のゲーム盤プレゼント:',
		contractNum:'局',

		yesterdaycoefficient:'昨日のゲーム数',
		dataTime:'時間',
		cancelOrder:'キャンセルするかどうか',
		rechargeAmount:'チャージ金額',
		placeRechargeAmount:'チャージ金額を入力してください',
		withdrawalAmount:'引き出し金額',
		PleaseWithdrawalAmount:'現金引き出し金額を記入してください',
		available:'利用可能',
		noData:'データなし',
		details:'詳細を見る',
		bureau:'局',
		communitylevel:'コミュニティレベル',
		level:'グレード',
		directPush:'ダイレクトプッシュ',
		myDirectUserRecord:'私の直接ユーザー記録',
		myDirectRecord:'私の直接の記録',
		revoked:'取り消された',
		processing: '処理',
		sell: '売る',
		buyIn: 'で買う',
		yesterdaycoefficient: '昨日のゲーム数',
		dataTime: '時間',
		cancelOrder: 'キャンセルするかどうか',
		rechargeAmount: 'チャージ金額',
		placeRechargeAmount: 'チャージ金額を入力してください',
		withdrawalAmount: '引き出し金額',
		PleaseWithdrawalAmount: '現金引き出し金額を記入してください',
		available: '利用可能',
		cumulativeCubQuantity: '累计CUB数量',
		cumulativeTlkQuantity: '累计TLK数量',
		currentExchangeRate: '現在の為替レート',
		game: 'ゲーム',
		officialAnnouncement: '公式発表',
		accountAssets: 'アカウントアセット',
		recharge: '再充電',
		withdrawal: '出金',
		orePool: '鉱池',
		DisneyTheLionKing: 'ライオンキング',
		newsFlash: 'クイックニュース',
		availableBalance: '利用可能な残高',
		frozenBalance: '冷凍バランス',
		totalBalance: '合計残高',
		assetRecords: '資産レコード',
		currency: '通貨',
		transferAddress: '転送アドレス',
		amountOfMoney: '金額',
		selectCurrency: '通貨の選択',
		pleaseSelectCurrency: '通貨を選択してください',
		PleaseFillInTheTransferAmount: '送金金額を入力してください',
		notes: '備考',
		optional: 'オプション',
		gameAssetBalance: 'ゲーム資産残高',
		minersExpenses: 'マイナー費用',
		nextStep: '次へ',
		pleaseInputPassword: 'パスワードを入力してください',
		determine: '決める',
		cancel: 'キャンセル',
		whole: 'すべて',
		incrementalRelease: '累積リリース',
		minePoolBalance: 'マイニングプールバランス',
		releaseCoefficient: '解放係数',
		releaseRecord: 'リリースレコード',
		noRecord: 'まだ記録がありません',
		withdrawalOfAssets: 'アセットの引き出し',
		lionKingDividendWeighted: 'ライオンキング配当配当加重',
		contract: '契約',
		test1: '永久加重配当40％ゲームマイナーの手数料',
		test2: '割り当てのみが残っています',
		name: '名前',
		buyNow: '今すぐスナップ',
		PromotionReward: 'プロモーション報酬',
		communityPromotionAward: 'コミュニティ推進賞',
		PromotionOfIncentiveRules: 'プロモーションインセンティブルール',
		communityLevel: 'コミュニティレベル',
		gamesCompletedToday: '今日の完了したゲーム',
		communityDividendCoefficient: 'コミュニティ配当係数',
		accumulatedCommunityDividendsObtained: '累積コミュニティ配当',
		yesterdayCommunityBonusAccumulated: '昨日のコミュニティ配当の累積',
		communityPromotionIncentiveRecord: 'コミュニティプロモーションインセンティブレコード',
		listOfCommunityPromotionIncentives: 'コミュニティプロモーションインセンティブリーダーボード',
		IndividualPromotionAward: '個人プロモーション賞',
		myPushRecord: '私のダイレクトプッシュレコード',
		usersHaveBeenPromotedDirectly: 'ユーザーは直接昇格されました',
		indirectlyPromotedUsers: '間接的に昇格されたユーザー',
		accumulatedIndividualPromotionAwards: '個人プロモーション報酬の累計',
		numberOfGamesDirectlyPromotedToday: '本日はゲームラウンド数を直接プロモートしました',
		numberOfGamesPromotedIndirectlyToday: '今日はゲームラウンド数を間接的に昇格しました',
		personalPromotionIncentiveRecord: 'パーソナルプロモーションインセンティブレコード',
		personalPromotionIncentiveRanking: 'パーソナルプロモーションインセンティブリーダーボード',
		shareMyPromotionAchievements: 'プロモーション記録を共有する',
		InviteMoreFriends: 'もっと友達を招待する',
		shareNow: '今すぐ共有',
		communityPromotionIncentive: 'コミュニティプロモーションインセンティブ',
		test3: 'システムが出る',
		test4: 'ユーザープロモーションを促進するために使用されます',
		test5: '10元の個人報酬+チーム報酬（すべてのプラットフォーム）',
		test6: 'チーム報酬（例:A1勝利,10元の30％がネットレベルに従って他の9人に分配されます）',
		test7: '毎日12時決済前日のデータ',
		personalPromotionIncentive: 'パーソナルプロモーションインセンティブ',
		test8: 'ダイレクトプッシュ,ユーザーがゲームをプレイするたびに0.2 TLKを獲得するように促進する',
		test9: 'ユーザーに紹介し,ゲームごとにTLKの0.1の値を取得するように宣伝します',
		time: '時間',
		number: '番号',
		noDataAvailable: '利用可能なデータはありません',
		user: 'ユーザー',
		incrementalCubQuantity: 'CUBの累計',
		myDirectPushUserRecord: '私のダイレクトプッシュユーザーレコード',
		myNumberOfDirectTweets: '私のダイレクトプッシュ番号',
		saveToAlbum: 'アルバムに保存',
		makeMoney: '友達を誘って一緒にお金を稼ぐ',
		erweima: '招待コード',
		saomiao: 'スキャンしてアプリを登録およびダウンロードする',
		lowPowerField: '低電力フィールド',
		bottomNote: 'ボトムノート',
		test10: '終日オープン固定ベット',
		test11: '時間制限オープンオプションの倍数',
		highPowerField: '高出力フィールド',
		leaveYourSeat: '座席を離れる',
		keepPlaying: '再生を続ける',
		test12: 'これ以上遊んで、休憩しないで',
		nickname: 'ニックネーム',
		accountID: 'アカウントID',
		totalGamesPlayed: 'プレイしたゲームの合計数',
		winningAuctionRate: 'オークションレートの取得',
		numberOfGamesAvailableToday: '今日のゲームでプレイ可能なゲーム数',
		contractGrade: '契約グレード',
		contractDailyGameNumberGift: '契約毎日ゲームラウンドギフト',
		contractExpirationTime: '契約有効期限',
		test13: '契約ロックTLK、より多くのゲーム時間を取得',
		contractRules: '契約ルール',
		test14: `1。新しく登録したユーザーは試用版ゲームを体験できます
			 2.ユーザーはゲームをプレイするために契約をロックする必要があります。異なる量のロックアップは異なる契約レベルに対応し、ゲームの各レベルは1日あたりのゲーム数に与えられます契約発効日とは異なります。 
			 3. 
			 V0（ロックポジション11JDT、1日の契約期間、毎日のゲームボードはギフト:10ラウンド）
			 V1（ロックポジション200JDT、7日の契約期間、毎日のゲームボードはギフト:50ラウンド）
			 V2（ロックポジション1648JDT、契約期間30日、1日のゲーム盤交付:100ラウンド）
			 V3（ロック位置4230JDT、契約期間60日、1日のゲーム盤交付:200ラウンド）
			 V4（ロック位置8248JDT、契約期間90日） 、毎日のゲーム盤の贈り物:400ラウンド）
			 V5（ロック位置21015JDT、契約期間180日、毎日のゲーム盤の贈り物:500ラウンド）`,
		lockUpAmount: 'ロック位置量',
		lockUp: 'ロック位置の決定',
		lockUpRecord: '倉庫レコードのロック',
		lockTime: 'ロック位置時間',
		myInvitationCode: '私の招待コード',
		copy: 'コピー',
		InvitationRelationship: '招待状',
		test15: 'クリックしてプロモーション特典を表示',
		accumulatedIncome: '累積利益',
		test16: '累積チケットフィードバックが取得されました',
		type: 'タイプ',
		ticketRebate: 'チケット控除',
		stake: '控除タイプ',
		reward: 'ゲーム控除',
		bgm: 'バックグラウンドミュージック',
		successfulAuction: '落札',
		congratulations: 'おめでとうございます',
		PrizeSettlement: '賞金決済',
		myPrize: '私の賞',
		otherPrizes: '残りの賞品',
		mine: '私の',
		CreateTheWorldMe: 'クリエーター',
		securitySetting: 'セキュリティ設定',
		aboutUs: '私たちについて',
		messageCenter: 'メッセージセンター',
		feedBack: 'フィードバック',
		exportWordMe: 'ニーモニックワードのエクスポート',
		exportPrivateKeyMe: '秘密鍵のエクスポート',
		updatePwd: 'パスワードの変更',
		confirmPwd: '確認',
		cancelPwd: 'キャンセル',
		pleasetakeGoodKey: 'あなたのニーモニックな言葉を大切にしてください',
		saveToAlbumKey: 'アルバムに保存',
		exportKeyTip: '秘密鍵を適切に保管してください。家に隔離し,ネットワークから離して,オフラインで保管することをお勧めします。秘密鍵がネットワークに接続されているときは,ストレージを共有しないでください。紛失を防ぐため,誰かが悪意を持って取得すると,修復不可能な資産の損失が発生する可能性があります。',
		copyPrivateKey: '秘密鍵のコピー',
		enterOldPwd: '古いパスワードを入力してください',
		placeEnterOldPwd: '古いパスワードを入力してください',
		enterNewPwd: '新しいパスワードを入力してください',
		placeEnterNewPwd: '新しいパスワードを入力してください',
		confirmNewPwd: '新しいパスワードの確認',
		placeConfirmNewPwd: '新しいパスワードを確認してください',
		confirmChange: '変更の確認',
		placeFeedBack: 'フィードバックしたい問題やコメントを教えてください',
		submitFeedBack: '送信',
		collectionWalletAddress: 'レシートウォレットアドレス',
		collectionWalletAddressPh: 'コレクションウォレットアドレスを入力してください',
		inputTransferAmount: '送金金額を入力してください',
		transferAmountRemark: '振込備考を記入してください',
		ServiceChargeTrans: '手数料',
		allMoney: 'すべて',
		addWalletAddress: '新しいウォレットアドレス',
		walletAddressType: 'アドレスタイプ',
		walletAddress: 'アドレス',
		ValidAddress: '有効なアドレスを入力してください',
		walletName: '名前',
		validName: '名前を入力してください',
		preservationAddress: '保存する',
		collectionTron: 'このアドレスはTRONの送金のみをサポートしています。他の通貨では使用しないでください',
		copyCollectionAddress: 'コレクションのアドレスをコピーする',
		indexOfficialAnnouncement: '公式発表',
		MyAssets: 'マイアセット',
		transferAmountIndex: '転送',
		collectionIndex: '領収書',
		oldPwdNull: '古いパスワードは空にできません',
		newPwdNull: '新しいパスワードは空にできません',
		confirmPwdNull: '確認パスワードは空にできません',
		twoPwdAtypism: '2つのパスワードに矛盾があります',
		blockchainBrowserView: 'ブロックチェーンブラウザーに移動して表示する',
		editAddressWallet: '住所の編集',
		addressNull: '住所が必要です',
		addressFormat: '住所の形式が正しくありません',
		nameNull: '名前が必要です',
		tronTransfer: 'TRON転送',
		currencyAccountNull: '通貨が必要です',
		walletAddressNull: 'ウォレットアドレスが必要です',
		transferAccountNull: '送金が必要です',
		transferAmountCannotBalance: '送金金額は残高を超えることはできません',
		availableBalance: '利用可能な残高は',
		tronTransferCollection: 'TRON送金',
		selectTransferAddress: '支払いウォレットの住所を選択してください',
		elephant: '象',
		leopard: 'ヒョウ',
		wolf: 'コヨーテ',
		tiger: 'リトルタイガー',
		reminder: '暖かいリマインダー',
		YourContractExpire: '契約がまもなく終了します',
		CreateWalletGuidPage: 'ウォレットガイドページの作成',
		pleaseOpenWallet: '最初のデジタルウォレットを開いてください',
		createWallet: 'ウォレットの作成',
		importWallet: 'ウォレットのインポート',
		created1: '低レベルのパブリックチェーンを選択する',
		testFail:"失敗",
		contractCopy:"ユーザーはゲームをプレイするために契約をロックする必要があります。ロックアップの量が異なると、契約レベルが異なります。ゲームの各レベルは、1日あたりのゲーム数に割り当てられます。ゲームの数と契約の日数は異なります。",

		testFail: "失敗",
		createdWallet: 'ウォレットの作成',
		walletName: 'ウォレット名',
		walletName_value: 'ウォレット名を入力してください',
		walletErr_value1: "ウォレット名が必要です",
		walletErr_value2: "3文字以上",
		walletErr_value3: "不正な文字が存在します",
		walletErr_value4: "名前は15文字を超えることはできません",

		setPassWord: 'パスワードの設定',
		setPassWord_value: "新しいパスワードを入力してください",
		PassWordErr_value1: "パスワードが必要です",
		PassWordErr_value2: "6文字以上",
		PassWordErr_value3: "パスワードには英語の数字が必要です！",
		PassWordErr_value4: "パスワードは15文字を超えることはできません！",
		PassWordErr_value5: "2つのパスワードに矛盾があります！",

		confirmPassWord: 'パスワードをもう一度入力してください',
		confirmPassWord_value: "パスワードをもう一度入力してください",
		showToast: '情報を入力してください',
		backup: 'バックアッププロンプト',
		backupTitle: "メモニーモニック",
		backupTaps: "ウォームヒント",
		backupValue: '取得するニーモニックワードはウォレットアセットの所有権に等しい',
		backupListVal: [{
				txt: 'ニーモニックは英語の単語で構成されています。正しくコピーして保管してください',
			},
			{
				txt: 'ニーモニックが見つからないため取得できません。必ずバックアップしてください',
			},
			{
				txt: "「スクリーンショットを共有したり,電子デバイスに保存したりしないでください。第三者によって悪意を持って収集され,資産が失われる可能性があります」"
			}
		],

		lock:'閉じ込める',
		contractPeriod:"契約サイクル",
		day:'日',
		everyday:"毎日のゲーム盤プレゼント",
		contractNum:"局",

		backups: 'ニーモニックワードのバックアップ',
		backupsVal: "ニーモニックワードを順番にバックアップ",

		testBackups: 'バックアップの確認',
		testBackupsVal: "ニーモニックワードを順番にクリックすると,正しくバックアップされたことを確認できました",

		importWallet: 'ウォレットのインポート',
		words: '覚え言葉',
		wordsTitle: "ニーモニックワードを順番に入力してください。ニーモニックワードを使用してウォレットをインポートするときにパスワードをリセットできます",
		wordsErrVal: 'ニーモニックワードが必要です',
		wordsVal: '覚えやすい単語をカンマで区切って入力してください',
		secretKey: '秘密鍵',
		secretKeyErrVal: "秘密鍵が必要です",
		secretKeyTitle: "TRON公式ウォレットのPrivateKeyの内容をコピーして入力ボックスに貼り付けるか,秘密鍵の内容をスキャンして生成されたQRコードをインポートしてください。大文字に注意してください",
		secretKeyVal: "秘密鍵を入力してください",
		secretKeyNext: 'インポート開始',

		more: "もっと",
		moreLists: [{
				icon: 'url(/static/index/more1.png)',
				cTitle: 'ホワイトペーパー',
				title: 'WHITE PAPER',
			},
			{
				icon: 'url(/static/index/more2.png)',
				cTitle: 'プロジェクトの概要',
				title: 'Project introduction',
			},
			{
				icon: 'url(/static/index/more3.png)',
				cTitle: 'ビデオリンク',
				title: 'Video link',
			},
			{
				icon: 'url(/static/index/more4.png)',
				cTitle: 'トランザクション',
				title: 'exchange',
				lists: [{
						address: 'zhongbi',
						url: "https://www.zb.live/cn/"
					},
					{
						address: 'huobi',
						url: "https://www.huobi.me"
					},
					{
						address: 'coinbase',
						url: "https://www.coinbase.com/"
					},
					{
						address: 'okex',
						url: "https://www.okex.me"
					}
				]
			},
			{
				icon: 'url(/static/index/more5.png)',
				cTitle: 'エコロジカルコンストラクション',
				title: 'Ecological construction',
			}
		],

		notice: "公式発表",
		news: 'エクスプレスニュース',
		checkoutWallet: 'ウォレットの切り替え',
		transaction: 'トランザクション',
		assets: 'アカウント資産',
		transactionTaps1: 'Transaction Market',
		transactionTaps2: "注文レコード",
		transactionTitle: '資産詳細',
		transactionListVal1: '利用可能な残高',
		transactionListVal2: 'フリーズバランス',
		transactionListVal3: 'マイニングプールの残高',
		transactionTotal: "合計残高",


		market: '取引市場',
		marketTaps: '市場状況の表示',
		marketBuy: '購入',
		marketSell: "販売",
		marketLeftTaps1: '5つの歯車',
		marketLeftTaps2: '詳細',
		fiveTitle1: "ハンディキャップ",
		fiveTitle2: "価格",
		fiveTitle3: "数量",
		fiveTitle4: "時間",
		fiveTitle4: "最新の取引",
		marketRightTaps1: "指値",
		marketRightTaps2: "市場価格",
		marketR_Title1: "価格",
		marketR_Title1Low: "市場価格",
		marketR_Title2: "数量",
		marketR_Title2Val: "数量を入力してください",
		marketR_Ava1: "利用可能",
		marketR_Ava2: "すべて",
		marketR_BottomVal: "トランザクション金額",

		market_24hTop: "24時間で最高",
		market_24hLow: "最低24時間",
		market_24hDeal: '24時間のボリューム ',
		marketDetailsVal1: '奥行き',
		marketDetailsVal2: '対処',
		marketListTitle1: '買い注文数',
		marketListTitle2: '価格',
		marketListTitle3: '販売数',
		marketListTitle4: '時間',
		marketListTitle5: '方向',
		marketListTitle6: '数量',

		order: '注文記録',
		orderTaps1: "委任されたレコード",
		orderTaps2: "取引記録",
		orderListVal1: "指値注文",
		orderListVal2: "完成した",
		orderListVal3: "取り消された",
		orderListVal4: "成行注文",
		orderListVal5: "平均価格",
		orderListVal6: "取引済み",
		orderListVal7: "合計トランザクション",
		orderListVal8: "手数料",
		orderListVal9: '取引金額',
		nextComplete: '完了',
		inDev: '乞うご期待！',
		addWallet: 'ウォレットを追加',
		importWallet: "ウォレットをインポート",
	},
	KoreanLanguage: {
		informationempty:'정보는 비워 둘 수 없습니다',
		thereOpenContract:'만료되지 않은 계약이 있습니다',
		undo:'실행 취소',
		notYetOpen:'아직 열지 않았습니다',
		lock:'잠그다',
		contractPeriod:'계약주기',
		day:"일",
		everyday:'매일 게임 보드 선물:',
		contractNum:'국',

		yesterdaycoefficient:'어제 플레이 한 게임 수',
		dataTime:'시각',
		cancelOrder:'취소 여부',
		rechargeAmount:'충전량',
		placeRechargeAmount:'충전량을 입력하십시오',
		withdrawalAmount:'인출 금액',
		PleaseWithdrawalAmount:'현금 인출 금액을 기입하십시오',
		available:'유효한',
		currentExchangeRate:'현재 환율',
		noData:'데이터가 없습니다',
		details:'자세히보다',
		bureau:'국',
		communitylevel:'커뮤니티 레벨',
		level:'등급',
		directPush:'직접 푸시',
		myDirectUserRecord:'내 직접 사용자 기록',
		myDirectRecord:'내 직접 기록',
		revoked:'해지',
		processing: '가공',
		sell: '팔다',
		buyIn: '구매',
		yesterdaycoefficient: '어제 플레이 한 게임 수',
		dataTime: '시각',
		cancelOrder: '취소 여부',
		rechargeAmount: '충전량',
		placeRechargeAmount: '충전량을 입력하십시오',
		withdrawalAmount: '인출 금액',
		PleaseWithdrawalAmount: '현금 인출 금액을 기입하십시오',
		available: '유효한',
		currentExchangeRate: '현재 환율',
		game: '게임',
		officialAnnouncement: '공식 발표',
		accountAssets: '계정 자산',
		recharge: '충전',
		withdrawal: '인출',
		orePool: '미네 풀',
		DisneyTheLionKing: '사자 왕',
		newsFlash: '빠른 소식',
		availableBalance: '사용 가능한 잔액',
		frozenBalance: '냉동 잔액',
		totalBalance: '총 잔액',
		assetRecords: '자산 레코드',
		currency: 'Currency',
		transferAddress: '전송 주소',
		amountOfMoney: 'Amount',
		selectCurrency: '통화 선택',
		pleaseSelectCurrency: '통화를 선택하십시오',
		PleaseFillInTheTransferAmount: '이체 금액을 입력하십시오',
		notes: '비고',
		optional: '선택 사항',
		gameAssetBalance: '게임 자산 잔액',
		minersExpenses: '광부 비용',
		nextStep: '다음',
		pleaseInputPassword: '비밀번호를 입력하십시오',
		determine: '결정',
		cancel: '취소',
		whole: '모두',
		cumulativeRelease: '누적 릴리스',
		minePoolBalance: '마이닝 풀 잔고',
		releaseCoefficient: '해제 계수',
		releaseRecord: '릴리스 레코드',
		noRecord: '아직 레코드 없음',
		withdrawalOfAssets: '자산 철수',
		lionKingDividendWeighted: '사자 왕 배당금 가중',
		contract: '계약',
		test1: '영구적 인 가중 배당 40 % 게임 광부 수수료',
		test2: '할당량 만 남았습니다',
		name: '이름',
		buyNow: '지금 구매',
		promotionReward: '프로모션 리워드',
		communityPromotionAward: '커뮤니티 프로모션 어워드',
		promotionOfIncentiveRules: '프로모션 인센티브 규칙',
		communityLevel: '커뮤니티 레벨',
		gamesCompletedToday: '오늘 완료된 게임',
		communityDividendCoefficient: '커뮤니티 배당 계수',
		accumulatedCommunityDividendsObtained: '누계 된 커뮤니티 배당금',
		yesterdayCommunityBonusAccumulated: '어제 누적 된 커뮤니티 배당금',
		communityPromotionIncentiveRecord: '커뮤니티 프로모션 인센티브 레코드',
		listOfCommunityPromotionIncentives: '커뮤니티 프로모션 인센티브 리더 보드',
		individualPromotionAward: '개인 프로모션 어워드',
		myPushRecord: '내 직접 푸시 레코드',
		usersHaveBeenPromotedDirectly: '사용자가 직접 승격되었습니다',
		indirectlyPromotedUsers: '간접적으로 승격 된 사용자',
		accumulatedIndividualPromotionAwards: '누적 개인 프로모션 보상',
		numberOfGamesDirectlyPromotedToday: '오늘은 게임 라운드 수를 직접 홍보했습니다.',
		numberOfGamesPromotedIndirectlyToday: '오늘은 게임 라운드 수를 간접적으로 승격했습니다',
		personalPromotionIncentiveRecord: '개인 프로모션 인센티브 레코드',
		personalPromotionIncentiveRanking: '개인 프로모션 인센티브 리더 보드',
		shareMyPromotionAchievements: '프로모션 기록 공유',
		inviteMoreFriends: '친구를 더 초대하십시오',
		shareNow: '지금 공유',
		communityPromotionIncentive: '커뮤니티 프로모션 인센티브',
		test3: '시스템이 나옵니다',
		test4: '사용자 홍보 장려',
		test5: '10 위안의 개별 보상 + 팀 보상 (모든 플랫폼) ',
		test6: '팀 보상 (예 : A1 당첨, 10 위안의 30 %가 순 수준에 따라 다른 9 명에게 분배됩니다)',
		test7: '매일 12시 정산 전날의 데이터',
		personalPromotionIncentive: '개인 프로모션 인센티브',
		test8: '직접 밀기, 사용자가 게임을 할 때마다 0.2 TLK를 얻도록 홍보',
		test9: '게임마다 TLK의 0.1 값을 얻도록 사용자를 소개하고 홍보하십시오',
		time: '시간',
		number: '숫자',
		noDataAvailable: '데이터 없음',
		user: '사용자',
		cumulativeCubQuantity: '누적 CUB 수량',
		cumulativeTlkQuantity: '누적 TLK 수량',
		myDirectPushUserRecord: '내 직접 푸시 사용자 레코드',
		myNumberOfDirectTweets: '내 직접 푸시 번호',
		saveToAlbum: '앨범에 저장',
		makeMoney: '친구를 모아서 돈을 벌어주세요',
		erweima: '초대 코드',
		saomiao: '앱 등록 및 다운로드 스캔',
		lowPowerField: '저전력 필드',
		bottomNote: '하단',
		test10: '하루 종일 고정 베팅 열기',
		test11: '개시 시간 제한 옵션 배수',
		highPowerField: '고출력 필드',
		leaveYourSeat: '좌석 떠나기',
		keepPlaying: '계속하기',
		test12: '더 이상 연주하지 말고 휴식을 취하십시오',
		nickname: '닉네임',
		accountID: '계정 ID',
		totalGamesPlayed: '총 게임 수',
		winningAuctionRate: '경매 율 얻기',
		numberOfGamesAvailableToday: '오늘의 게임 가능한 게임 수',
		contractGrade: '계약 등급',
		contractDailyGameNumberGift: '계약 일일 게임 라운드 선물',
		contractExpirationTime: '계약 만료 시간',
		test13: '계약 잠금 TLK, 더 많은 게임 시간 확보',
		contractRules: '계약 규칙',
		test14: `1. 새로 등록한 사용자는 평가판 게임을 경험할 수 있습니다 
			 2. 사용자는 게임을하기 위해 계약을 잠글 필요가 있습니다. 다른 잠금 수준은 계약 레벨에 따라 다르며, 게임의 각 레벨은 하루에 게임 수에 제공됩니다 계약 발효 일과 다릅니다. 
			 3.
			  V0 (잠금 위치 11JDT, 계약 기간 1 일, 일일 게임 보드는 선물 : 10 라운드) 
			  V1 (잠금 위치 200JDT, 계약 기간 7 일, 매일 게임 보드는 선물 : 50 라운드) 
			  V2 (잠금 위치 1648JDT, 계약 기간 30 일, 일일 게임 보드 부여 : 100 라운드) 
			  V3 (잠금 위치 4230JDT, 계약 기간 60 일, 일일 게임 보드 부여 : 200 라운드) 
			  V4 (잠금 위치 8248JDT, 계약 기간 90 일) , 일일 게임 보드 선물 : 400 라운드)
			   V5 (잠긴 위치 21015JDT, 계약 기간 180 일, 일일 게임 보드 선물 : 500 라운드)`,
		lockUpAmount: '잠금 위치 금액',
		lockUp: '잠금 위치 결정',
		lockUpRecord: '창고 기록 잠금',
		lockTime: '잠금 위치 시간',
		myInvitationCode: '내 초대 코드',
		copy: '복사',
		invitationRelationship: '초대 관계',
		test15: '홍보 보상을 보려면 클릭하십시오',
		accumulatedIncome: '누적 이익',
		test16: '누적 티켓 피드백을 얻었습니다',
		type: '유형',
		ticketRebate: '티켓 공제',
		stake: '공제 유형',
		reward: '게임 공제',
		bgm: '배경 음악',
		successfulAuction: '성공적인 입찰',
		congratulations: '축하합니다',
		awardSettlement: 'Prize 결제',
		myPrize: '내 상',
		otherPrizes: '남은 상',
		mine: '광산',
		CreateTheWorldMe: '크리에이티브 월드',
		securitySetting: '보안 설정',
		aboutUs: '회사 소개',
		messageCenter: '메시지 센터',
		feedBack: '피드백',
		exportWordMe: '니모닉 단어 내보내기',
		exportPrivateKeyMe: '개인 키 내보내기',
		updatePwd: '비밀번호 변경',
		confirmPwd: '확인',
		cancelPwd: '취소',
		pleasetakeGoodKey: '니모닉 단어를 잘 관리하십시오',
		saveToAlbumKey: '앨범에 저장',
		exportKeyTip: '개인 키를 올바르게 보관하십시오. 오프라인으로 저장하고 집과 격리하고 네트워크에서 멀리 떨어진 곳에 보관하는 것이 좋습니다.',
		copyPrivateKey: '개인 키 복사',
		enterOldPwd: '이전 비밀번호 입력',
		placeEnterOldPwd: '이전 비밀번호를 입력하십시오',
		enterNewPwd: '새 비밀번호 입력',
		placeEnterNewPwd: '새 비밀번호를 입력하십시오',
		confirmNewPwd: '새 비밀번호 확인',
		placeConfirmNewPwd: '새 비밀번호를 확인하십시오',
		confirmChange: '변경 사항 확인',
		placeFeedBack: '문제 나 의견을 말 해주세요.',
		submitFeedBack: '제출',
		collectionWalletAddress: '영수증 지갑 주소',
		collectionWalletAddressPh: '수집 지갑 주소를 입력하십시오',
		inputTransferAmount: '이체 금액을 입력하십시오',
		transferAmountRemark: '이전 비고를 작성하십시오',
		ServiceChargeTrans: '취급 수수료',
		allMoney: '모두',
		addWalletAddress: '새 지갑 주소',
		walletAddressType: '주소 유형',
		walletAddress: '주소',
		ValidAddress: '유효한 주소를 입력하십시오',
		walletName: '이름',
		validName: '이름을 입력하십시오',
		preservationAddress: '저장',
		collectionTron: '이 주소는 TRON 송금 만 지원합니다. 다른 통화로 사용하지 마십시오.',
		copyCollectionAddress: '복사 모음 주소',
		indexOfficialAnnouncement: '공식 발표',
		MyAssets: '내 자산',
		transferAmountIndex: '전송',
		collectionIndex: '영수증',
		oldPwdNull: '오래된 암호는 비워 둘 수 없습니다',
		newPwdNull: '새 비밀번호는 비워 둘 수 없습니다',
		confirmPwdNull: '비밀번호를 비울 수 없습니다',
		twoPwdAtypism: '두 개의 암호가 일치하지 않습니다',
		blockchainBrowserView: '보려면 블록 체인 브라우저로 가십시오',
		editAddressWallet: '주소 수정',
		addressNull: '주소가 필요합니다',
		addressFormat: '주소 형식이 잘못되었습니다',
		nameNull: '이름은 필수입니다',
		tronTransfer: '트론 전송',
		currencyAccountNull: '통화가 필요합니다',
		walletAddressNull: '월렛 주소가 필요합니다',
		transferAccountNull: '이체 금액이 필요합니다',
		transferAmountCannotBalance: '이체 금액은 잔액보다 클 수 없습니다',
		availableBalance: '사용 가능한 잔액은',
		tronTransferCollection: 'TRON 송금',
		selectTransferAddress: '지급 지갑 주소 선택',
		elephant : '코끼리 왕',
		leopard : '표범',
		wolf : '코요테',
		tiger : '작은 호랑이',
		reminder : '따뜻한 알림',
		YourContractExpire : '계약이 만료 되려고합니다',
		CreateWalletGuidPage : '지갑 가이드 페이지 만들기',
		pleaseOpenWallet : '첫 번째 전자 지갑을여십시오',
		createWallet : '지갑 만들기',
		importWallet : '지갑 가져 오기',
		created1 : '낮은 수준의 공개 체인 선택',
		testFail:"실패",
		contractCopy:"사용자는 게임을하기 위해 계약을 잠 가야합니다. 다른 잠금 수준은 다른 계약 수준에 해당합니다. 게임의 각 수준은 하루에 게임 수를 선물합니다. 게임의 수와 계약의 유효 일수가 다릅니다.",
		
		createdWallet : '지갑 만들기',
		walletName : '월렛 이름',
		walletName_value : '지갑 이름을 입력하십시오',
		walletErr_value1 : "월렛 이름이 필요합니다",
		walletErr_value2 : "3 자 이상",
		walletErr_value3 : "잘못된 문자가 있습니다",
		walletErr_value4 : "이름은 15자를 초과 할 수 없습니다",
		
		setPassWord : '비밀번호 설정',
		setPassWord_value : "새 비밀번호를 입력하십시오",
		PassWordErr_value1 : "비밀번호가 필요합니다",
		PassWordErr_value2 : "6 자 이상",
		PassWordErr_value3 : "암호에는 영어 숫자가 있어야합니다!",
		PassWordErr_value4 : "암호는 15자를 초과 할 수 없습니다!",
		PassWordErr_value5 : "두 개의 암호가 일치하지 않습니다!",
		
		confirmPassWord : '비밀번호를 다시 입력하십시오',
		confirmPassWord_value : "비밀번호를 다시 입력하십시오",
		showToast : '정보를 입력하십시오',
		
		backup : '백업 프롬프트',
		backupTitle : "메모 니모닉",
		backupTaps : "따뜻한 팁",
		backupValue : '니모닉 단어를 얻는 것은 지갑 자산의 소유권과 같습니다.',
		backupListVal : 
		[
			{
				txt : '니모닉은 영어 단어로 구성되어 있습니다. 복사하여 올바르게 보관하십시오',
			},
		],
		elephant: '코끼리 왕',
		leopard: '표범',
		wolf: '코요테',
		tiger: '작은 호랑이',
		reminder: '따뜻한 알림',
		YourContractExpire: '계약이 만료 되려고합니다',
		CreateWalletGuidPage: '지갑 가이드 페이지 만들기',
		pleaseOpenWallet: '첫 번째 전자 지갑을여십시오',
		createWallet: '지갑 만들기',
		importWallet: '지갑 가져 오기',
		created1: '낮은 수준의 공개 체인 선택',
		testFail: "실패",

		createdWallet: '지갑 만들기',
		walletName: '월렛 이름',
		walletName_value: '지갑 이름을 입력하십시오',
		walletErr_value1: "월렛 이름이 필요합니다",
		walletErr_value2: "3 자 이상",
		walletErr_value3: "잘못된 문자가 있습니다",
		walletErr_value4: "이름은 15자를 초과 할 수 없습니다",

		setPassWord: '비밀번호 설정',
		setPassWord_value: "새 비밀번호를 입력하십시오",
		PassWordErr_value1: "비밀번호가 필요합니다",
		PassWordErr_value2: "6 자 이상",
		PassWordErr_value3: "암호에는 영어 숫자가 있어야합니다!",
		PassWordErr_value4: "암호는 15자를 초과 할 수 없습니다!",
		PassWordErr_value5: "두 개의 암호가 일치하지 않습니다!",

		confirmPassWord: '비밀번호를 다시 입력하십시오',
		confirmPassWord_value: "비밀번호를 다시 입력하십시오",
		showToast: '정보를 입력하십시오',

		backup: '백업 프롬프트',
		backupTitle: "메모 니모닉",
		backupTaps: "따뜻한 팁",
		backupValue: '니모닉 단어를 얻는 것은 지갑 자산의 소유권과 같습니다.',
		backupListVal: [
			{
				txt: '니모닉은 영어 단어로 구성되어 있습니다. 복사하여 올바르게 보관하십시오',
			},
			{
				txt: '니모닉이 없어서 검색 할 수 없습니다. 백업 해주세요',
			},
			{
				txt: "스크린 샷을 공유하거나 전자 장치에 저장하지 마십시오. 제 3자가 악의적으로 수집하여 자산이 손실 될 수 있습니다"
			}
		],

		lock:'잠그다',
		contractPeriod:"계약주기",
		day:'일',
		everyday:"매일 게임 보드 선물",
		contractNum:"국",
		
		backups : '백업 니모닉 단어',
		backupsVal : "니모닉 단어 백업 순서대로",
		
		testBackups : '백업 확인',
		testBackupsVal : "니모닉 단어를 순서대로 클릭하면 올바르게 백업되었음을 확인했습니다.",
		
		importWallet : '지갑 가져 오기',
		words : '니모닉 단어',
		wordsTitle : "니모닉 단어를 순서대로 입력하고 니모닉 단어를 사용하여 지갑을 가져 오는 동안 비밀번호를 재설정 할 수 있습니다",
		wordsErrVal : '니모닉 단어가 필요합니다',
		wordsVal : '니모닉 단어를 쉼표로 구분하여 입력하십시오',
		secretKey : '개인 키',
		secretKeyErrVal : "개인 키가 필요합니다",
		secretKeyTitle : "TRON 공식 지갑의 PrivateKey 컨텐츠를 입력 상자에 복사하여 붙여 넣거나 Private Key 컨텐츠를 스캔하여 생성 된 QR 코드를 가져 오십시오. 대문자에주의하십시오",
		secretKeyVal : "개인 키를 입력하십시오",
		secretKeyNext : '가져 오기 시작',
		
		more : "더보기",
		moreLists : [
			{
			icon : 'url (/static/index/more1.png)',
			cTitle : '백서',
			title : 'WHITE PAPER',
			}],
		backups: '백업 니모닉 단어',
		backupsVal: "니모닉 단어 백업 순서대로",

		testBackups: '백업 확인',
		testBackupsVal: "니모닉 단어를 순서대로 클릭하면 올바르게 백업되었음을 확인했습니다.",

		importWallet: '지갑 가져 오기',
		words: '니모닉 단어',
		wordsTitle: "니모닉 단어를 순서대로 입력하고 니모닉 단어를 사용하여 지갑을 가져 오는 동안 비밀번호를 재설정 할 수 있습니다",
		wordsErrVal: '니모닉 단어가 필요합니다',
		wordsVal: '니모닉 단어를 쉼표로 구분하여 입력하십시오',
		secretKey: '개인 키',
		secretKeyErrVal: "개인 키가 필요합니다",
		secretKeyTitle: "TRON 공식 지갑의 PrivateKey 컨텐츠를 입력 상자에 복사하여 붙여 넣거나 Private Key 컨텐츠를 스캔하여 생성 된 QR 코드를 가져 오십시오. 대문자에주의하십시오",
		secretKeyVal: "개인 키를 입력하십시오",
		secretKeyNext: '가져 오기 시작',

		more: "더보기",
		moreLists: [
			{
				icon: 'url (/static/index/more1.png)',
				cTitle: '백서',
				title: 'WHITE PAPER',
			},
			{
				icon: 'url (/static/index/more2.png)',
				cTitle: '프로젝트 소개',
				title: 'Project introduction',
			},
			{
				icon: 'url (/static/index/more3.png)',
				cTitle: '비디오 링크',
				title: 'Video link',
			},
			{
				icon: 'url (/static/index/more4.png)',
				cTitle: '교환',
				title: 'exchange',
				lists: [
					{
						address: 'zhongbi',
						url: "https://www.zb.live/cn/"
					},
					{
						address: 'huobi',
						url: "https://www.huobi.me"
					},
					{
						address: 'coinbase',
						url: "https://www.coinbase.com/"
					},
					{
						address: 'okex',
						url: "https://www.okex.me"
					}
				]
			},
			{
				icon: 'url (/static/index/more5.png)',
				cTitle: '생태 건설',
				title: 'Ecological construction',
			}
		],

		notice: "공식 발표",
		news: '뉴스',

		checkoutWallet: '지갑 전환',

		transaction: '거래',
		assets: '계정 자산',
		transactionTaps1: '거래 시장',
		transactionTaps2: "주문 레코드",
		transactionTitle: '자산 세부 사항',
		transactionListVal1: '사용 가능한 잔액',
		transactionListVal2: '고정 잔액',
		transactionListVal3: '마이닝 풀 잔고',
		transactionTotal: "총 잔액",

		market: '무역 시장',
		marketTaps: '시장 상황보기',
		marketBuy: '구매',
		marketSell: "판매",
		marketLeftTaps1: '5 개의 기어',
		marketLeftTaps2: '세부 사항',
		fiveTitle1: "핸디캡",
		fiveTitle2: "가격",
		fiveTitle3: "수량",
		fiveTitle4: "시간",
		fiveTitle4: "최신 거래",
		marketRightTaps1: "한정 가격",
		marketRightTaps2: "시장 가격",
		marketR_Title1: "가격",
		marketR_Title1: "시장 가격",
		marketR_Title2: "수량",
		marketR_Title2Val: "수량을 입력하십시오",
		marketR_Ava1: "사용 가능",
		marketR_Ava2: "모두",
		marketR_BottomVal: "거래 금액",

		market_24hTop: "24 시간 최고",
		market_24hLow: "24 시간 최소",
		market_24hDeal: '24 시간 거래량 ',
		marketDetailsVal1: 'Depth',
		marketDetailsVal2: '거래',
		marketListTitle1: '구매 주문 수',
		marketListTitle2: 'price',
		marketListTitle3: '판매 횟수',
		marketListTitle4: 'Time',
		marketListTitle5: '방향',
		marketListTitle6: '수량',

		order: '주문 기록',
		orderTaps1: "위임 된 레코드",
		orderTaps2: "거래 기록",
		orderListVal1: "제한 주문",
		orderListVal2: "완료",
		orderListVal3: "철회",
		orderListVal4: "시장 주문",
		orderListVal5: "평균 가격",
		orderListVal6: "Dealed",
		orderListVal7: "총 거래",
		orderListVal8: "취급 수수료",
		orderListVal9: '거래 금액',
		nextComplete: '완료',
		inDev: '기대！',
		addWallet: '지갑 추가',
		importWallet: "수입 지갑",
	},
}
